sudo: required
services:
  - docker

before_install:
  - docker build -t henryszecy/react-test -f  ./client/dev.Dockerfile ./client

script:
  - docker run henryszecy/react-test npm test -- --coverage

after_success:
  - docker build -t henryszecy/multi-client ./client
  - docker build -t henryszecy/multi-nginx ./nginx
  - docker build -t henryszecy/multi-server ./server
  - docker build -t henryszecy/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to dockers
  - docker push henryszecy/multi-client
  - docker push henryszecy/multi-nginx
  - docker push henryszecy/multi-server
  - docker push henryszecy/multi-worker  