sudo: required
services:
  - docker

before_install:
  - docker build -t henryszecy/react-test -f  ./client/dev.Dockerfile ./client


script:
  - docker run -e CI=true henryszecy/react-test npm run test -- --coverage

after_success:
  - docker build -t henrysze/multi-client ./client
  - docker build -t henrysze/multi-nginx ./nginx
  - docker build -t henrysze/multi-server ./server
  - docker build -t henrysze/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push henrysze/multi-client:latest
  - docker push henrysze/multi-nginx:latest
  - docker push henrysze/multi-server:latest
  - docker push henrysze/multi-worker:latest